<?php
namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use App\Models\{Order,Payment,RestaurantTable};
use App\Services\{CartService,MidtransService,OrderService};
use Illuminate\Http\{RedirectResponse,Request};
use Illuminate\Validation\{Rule,ValidationException};
use Illuminate\View\View;
class CheckoutController extends Controller {
 public function __construct(private readonly CartService $carts,private readonly OrderService $orders,private readonly MidtransService $midtrans){}
 public function create():View{$cart=$this->carts->getCart();$cart->load(['items.menuItem','items.menuPackage.items.menuItem']);abort_if($cart->items->isEmpty(),422,'Cart is empty.');return view('users.checkout.create',['cart'=>$cart,'subtotal'=>$this->carts->total($cart),'tables'=>RestaurantTable::active()->orderBy('table_number')->get(),'scannedTable'=>RestaurantTable::active()->find(session('scanned_restaurant_table_id'))]);}
 public function store(Request $r):RedirectResponse{$d=$r->validate(['order_type'=>['required',Rule::in([Order::TYPE_DINE_IN,Order::TYPE_DELIVERY,Order::TYPE_ROOM_SERVICE])],'customer_name'=>'required|string|max:150','customer_phone'=>'required|string|max:30','customer_email'=>'nullable|email|max:255','restaurant_table_id'=>'nullable|integer|exists:restaurant_tables,id','room_number'=>'nullable|string|max:30','delivery_address'=>'nullable|string|max:1000','guest_count'=>'required|integer|min:1|max:50','payment_timing'=>['required',Rule::in([Order::TIMING_PAY_NOW,Order::TIMING_PAY_LATER])],'customer_note'=>'nullable|string|max:1000','scheduled_at'=>'nullable|date|after_or_equal:now']);$fromQr=false;$tableId=null;if($d['order_type']===Order::TYPE_DINE_IN){$fromQr=(bool)session('scanned_restaurant_table_id');$tableId=$fromQr?(int)session('scanned_restaurant_table_id'):($d['restaurant_table_id']??null);if(!$tableId)throw ValidationException::withMessages(['restaurant_table_id'=>'Select or scan a table.']);}if($d['order_type']===Order::TYPE_DELIVERY&&empty($d['delivery_address']))throw ValidationException::withMessages(['delivery_address'=>'Delivery address is required.']);if($d['order_type']===Order::TYPE_ROOM_SERVICE&&empty($d['room_number']))throw ValidationException::withMessages(['room_number'=>'Room number is required.']);if($d['payment_timing']===Order::TIMING_PAY_LATER&&(!$fromQr||$d['order_type']!==Order::TYPE_DINE_IN))throw ValidationException::withMessages(['payment_timing'=>'Pay later is only available from a valid table QR.']);if($d['payment_timing']===Order::TIMING_PAY_NOW&&!config('midtrans.server_key'))throw ValidationException::withMessages(['payment_timing'=>'Configure MIDTRANS_SERVER_KEY in .env first.']);$cart=$this->carts->getCart();$cart->load(['items.menuItem','items.menuPackage.items.menuItem']);if($cart->items->isEmpty())throw ValidationException::withMessages(['cart'=>'Cart is empty.']);$result=$this->orders->checkout($d,$cart,$tableId,$fromQr);$order=$result['order'];$payment=$result['payment'];if($payment){try{$payment->update(['snap_token'=>$this->midtrans->createSnapToken($order,$payment)]);}catch(\Throwable $e){report($e);$payment->update(['status'=>Payment::STATUS_FAILED,'failed_at'=>now(),'note'=>'Snap token creation failed.']);$order->update(['payment_status'=>Order::PAYMENT_FAILED]);return redirect()->route('orders.show',['order'=>$order,'token'=>$order->access_token])->withErrors(['payment'=>'Order saved, but Midtrans token creation failed.']);}return redirect()->route('payments.show',['payment'=>$payment,'token'=>$order->access_token]);}return redirect()->route('orders.show',['order'=>$order,'token'=>$order->access_token])->with('success','Order confirmed. Pay at cashier later.');}
}
