<?php
namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use App\Models\{RestaurantTable,TableReservation};
use Carbon\Carbon;
use Illuminate\Http\{JsonResponse,RedirectResponse,Request};
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;
class ReservationController extends Controller {
 public function create():View{return view('users.reservations.create',['tables'=>RestaurantTable::active()->orderBy('capacity')->get()]);}
 private function unavailable(Carbon $start,Carbon $end){return TableReservation::whereIn('status',[TableReservation::STATUS_PENDING,TableReservation::STATUS_CONFIRMED,TableReservation::STATUS_SEATED])->where('reservation_start','<',$end)->where('reservation_end','>',$start);}
 public function availableTables(Request $request):JsonResponse{$data=$request->validate(['reservation_start'=>'required|date|after:now','duration_minutes'=>'required|integer|min:30|max:360','guest_count'=>'required|integer|min:1|max:50']);$start=Carbon::parse($data['reservation_start']);$end=$start->copy()->addMinutes($data['duration_minutes']);return response()->json(RestaurantTable::active()->where('capacity','>=',$data['guest_count'])->whereNotIn('id',$this->unavailable($start,$end)->pluck('restaurant_table_id'))->orderBy('capacity')->get());}
 public function store(Request $request):RedirectResponse{$data=$request->validate(['restaurant_table_id'=>'required|exists:restaurant_tables,id','customer_name'=>'required|string|max:150','customer_phone'=>'required|string|max:30','customer_email'=>'nullable|email|max:255','guest_count'=>'required|integer|min:1|max:50','reservation_start'=>'required|date|after:now','duration_minutes'=>'required|integer|min:30|max:360','special_request'=>'nullable|string|max:1000']);$table=RestaurantTable::active()->findOrFail($data['restaurant_table_id']);if($data['guest_count']>$table->capacity)throw ValidationException::withMessages(['guest_count'=>"Maximum capacity is {$table->capacity}."]);$start=Carbon::parse($data['reservation_start']);$end=$start->copy()->addMinutes($data['duration_minutes']);if($this->unavailable($start,$end)->where('restaurant_table_id',$table->id)->exists())throw ValidationException::withMessages(['reservation_start'=>'This table is already reserved.']);$reservation=TableReservation::create(['access_token'=>(string)Str::uuid(),'reservation_number'=>'RSV-'.now()->format('YmdHis').'-'.Str::upper(Str::random(5)),'user_id'=>auth()->id(),'restaurant_table_id'=>$table->id,'customer_name'=>$data['customer_name'],'customer_phone'=>$data['customer_phone'],'customer_email'=>$data['customer_email']??null,'guest_count'=>$data['guest_count'],'reservation_start'=>$start,'reservation_end'=>$end,'status'=>TableReservation::STATUS_PENDING,'special_request'=>$data['special_request']??null]);return redirect()->route('reservations.show',['reservation'=>$reservation,'token'=>$reservation->access_token])->with('success','Reservation submitted.');}
 public function show(Request $request,TableReservation $reservation):View{$allowed=hash_equals($reservation->access_token,(string)$request->query('token'))||(auth()->check()&&($reservation->user_id===auth()->id()||auth()->user()->isStaffOrAdmin()));abort_unless($allowed,403);return view('users.reservations.show',['reservation'=>$reservation->load('restaurantTable')]);}
 public function cancel(Request $request,TableReservation $reservation):RedirectResponse{$allowed=hash_equals($reservation->access_token,(string)$request->input('token'))||(auth()->check()&&$reservation->user_id===auth()->id());abort_unless($allowed,403);abort_if(in_array($reservation->status,[TableReservation::STATUS_COMPLETED,TableReservation::STATUS_CANCELLED],true),422);$reservation->update(['status'=>TableReservation::STATUS_CANCELLED,'cancellation_reason'=>$request->validate(['reason'=>'required|string|max:500'])['reason']]);return back()->with('success','Reservation cancelled.');}
}
